steps:
- name: 'tf1_opencv'
  args:
  - --dockerfile=imagr/dockerfile/tf1_with_opencv/Dockerfile
  - --destination=australia-southeast1-docker.pkg.dev/$PROJECT_ID/ml/tf1_with_opencv:$BRANCH_NAME
  - --destination=australia-southeast1-docker.pkg.dev/$PROJECT_ID/ml/tf1_with_opencv:$SHORT_SHA
  - --context=.
  - --cache=true
  waitFor: ['-']
- name: 'tf1_objection'
  args:
  - --dockerfile=imagr/dockerfile/object_detection/tf1/Dockerfile
  - --destination=australia-southeast1-docker.pkg.dev/$PROJECT_ID/ml/object_detection_tf1:$BRANCH_NAME
  - --destination=australia-southeast1-docker.pkg.dev/$PROJECT_ID/ml/object_detection_tf1:$SHORT_SHA
  - --context=.
  - --cache=true
  waitFor: ['tf1_opencv']

timeout: 7200s